In [1]:
import numpy as np

Create a 1D array

In [2]:
a = np.array([10,20,30,40,50])

print(a)

[10 20 30 40 50]


Check Data Type

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
b = np.array([
    [1,2,3],
    [4,5,6]
])

print(b)

[[1 2 3]
 [4 5 6]]


Create Zeros array

In [5]:
zeros = np.zeros((3,4))

print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
ones = np.ones((2,5))

print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
identity = np.eye(4)

print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Create an array using arrange()

In [8]:
arr = np.arange(1,11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


Create equally Spaced Numbers

In [9]:
lin = np.linspace(0,100,11)

print(lin)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


Indexing

In [10]:
print(arr[0])
print(arr[4])
print(arr[-1])

1
5
10


Slicing

In [11]:
print(arr[2:7])

[3 4 5 6 7]


Modifying elements

In [12]:
arr[0]=100

print(arr)

[100   2   3   4   5   6   7   8   9  10]


Access row and column

In [13]:
matrix=np.array([[10,20,30],
                 [40,50,60],
                 [70,80,90]])

print(matrix[1])

print(matrix[:,1])

[40 50 60]
[20 50 80]


Mathematical Operations

In [14]:
a=np.array([1,2,3])

b=np.array([4,5,6])

print(a+b)

[5 7 9]


In [15]:
print(a*b)

[ 4 10 18]


Statistics

In [16]:
marks=np.array([80,90,75,95,88])

print("Mean =",np.mean(marks))
print("Median =",np.median(marks))
print("Maximum =",np.max(marks))
print("Minimum =",np.min(marks))
print("Standard Deviation =",np.std(marks))

Mean = 85.6
Median = 88.0
Maximum = 95
Minimum = 75
Standard Deviation = 7.172168430816444


In [17]:
marks = np.array([
    [78, 85, 90],
    [67, 74, 80],
    [92, 88, 95],
    [56, 60, 58],
    [81, 79, 84]
])

subjects = ["Math", "Science", "English"]

print("Student Marks Analyzer\n")

for i in range(len(marks)):
    total = np.sum(marks[i])
    average = np.mean(marks[i])
    highest = np.max(marks[i])
    lowest = np.min(marks[i])

    if average >= 90:
        grade = "A+"
    elif average >= 80:
        grade = "A"
    elif average >= 70:
        grade = "B"
    elif average >= 60:
        grade = "C"
    else:
        grade = "D"

    print(f"Student {i+1}")
    print("Marks:", marks[i])
    print("Total:", total)
    print("Average:", round(average, 2))
    print("Highest:", highest)
    print("Lowest:", lowest)
    print("Grade:", grade)
    print("-" * 30)

print("\nSubject-wise Statistics")

for i in range(len(subjects)):
    print(subjects[i])
    print("Average:", round(np.mean(marks[:, i]), 2))
    print("Highest:", np.max(marks[:, i]))
    print("Lowest:", np.min(marks[:, i]))
    print()

Student Marks Analyzer

Student 1
Marks: [78 85 90]
Total: 253
Average: 84.33
Highest: 90
Lowest: 78
Grade: A
------------------------------
Student 2
Marks: [67 74 80]
Total: 221
Average: 73.67
Highest: 80
Lowest: 67
Grade: B
------------------------------
Student 3
Marks: [92 88 95]
Total: 275
Average: 91.67
Highest: 95
Lowest: 88
Grade: A+
------------------------------
Student 4
Marks: [56 60 58]
Total: 174
Average: 58.0
Highest: 60
Lowest: 56
Grade: D
------------------------------
Student 5
Marks: [81 79 84]
Total: 244
Average: 81.33
Highest: 84
Lowest: 79
Grade: A
------------------------------

Subject-wise Statistics
Math
Average: 74.8
Highest: 92
Lowest: 56

Science
Average: 77.2
Highest: 88
Lowest: 60

English
Average: 81.4
Highest: 95
Lowest: 58

